//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kutuphaneWeb_24_02_24
{
    using System;
    using System.Collections.Generic;
    
    public partial class islemlerTBL
    {
        public int islemID { get; set; }
        public Nullable<int> uyeID { get; set; }
        public Nullable<int> kitapID { get; set; }
        public Nullable<bool> islemTur { get; set; }
        public Nullable<System.DateTime> islemTarihi { get; set; }
    
        public virtual kitaplarTBL kitaplarTBL { get; set; }
        public virtual uyelerTBL uyelerTBL { get; set; }
    }
}
