//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kutuphaneWeb_24_02_24
{
    using System;
    using System.Collections.Generic;
    
    public partial class kitaplarTBL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public kitaplarTBL()
        {
            this.islemlerTBL = new HashSet<islemlerTBL>();
        }
    
        public int id { get; set; }
        public string kitapAd { get; set; }
        public string kitapYazar { get; set; }
        public string sayfaSayisi { get; set; }
        public Nullable<bool> aktiflik { get; set; }
        public Nullable<bool> oduncDurum { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<islemlerTBL> islemlerTBL { get; set; }
    }
}
