//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kutuphaneWeb_24_02_24
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class kutuphane_24_02_24Entities : DbContext
    {
        public kutuphane_24_02_24Entities()
            : base("name=kutuphane_24_02_24Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<islemlerTBL> islemlerTBL { get; set; }
        public virtual DbSet<kitaplarTBL> kitaplarTBL { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<uyelerTBL> uyelerTBL { get; set; }
    
        public virtual ObjectResult<GetLatestBookTransactions_Result> GetLatestBookTransactions(Nullable<int> uyeID)
        {
            var uyeIDParameter = uyeID.HasValue ?
                new ObjectParameter("uyeID", uyeID) :
                new ObjectParameter("uyeID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetLatestBookTransactions_Result>("GetLatestBookTransactions", uyeIDParameter);
        }
    }
}
